#!/usr/bin/env bash
# Declarative Postgres migration for des-web, via dpm
# (https://github.com/declarative-migrations/declarative-postgres-migrate.rs).
#
# Desired state = the shared pg-defs contract (libs/pg-defs/schema/schema.sql,
# git submodule of ORESoftware/k8s-libs-and-shared-defs) concatenated with this
# repo's overlay (schema/des-web.sql). The target database — AWS RDS in prod,
# Supabase or local Postgres in dev — converges onto that combined file. dpm
# materializes it on a shadow server, introspects both sides from pg_catalog,
# and emits ordered, reviewable SQL. Same contract as pg-defs/scripts/dpm.sh.
#
# Usage:
#   scripts/dpm.sh diff        # print the migration SQL (default; never executes)
#   scripts/dpm.sh verify      # rehearse on a shadow replica, prove convergence
#   scripts/dpm.sh review      # diff + AI review of the migration
#   scripts/dpm.sh apply       # generate + execute (interactive confirm)
#   scripts/dpm.sh bootstrap   # full DDL for an empty database
# Extra arguments pass through to dpm (e.g. --fail-on-diff, --out FILE).
#
# Env:
#   TARGET_DATABASE_URL   database to converge; falls back (in order) to
#                         AGENT_TASKS_RDS_DATABASE_URL, RDS_DATABASE_URL,
#                         DATABASE_URL, PG_DATABASE_URL, SUPABASE_DB_URL.
#   SHADOW_DATABASE_URL   a server where dpm may CREATE/DROP throwaway
#                         databases. Never point this at production. For
#                         Supabase targets use a LOCAL shadow server — Supabase
#                         poolers don't allow create/drop database.
#
# Safety: destructive statements are emitted commented-out, and `apply` refuses
# to execute live destructive SQL, unless dpm's two consent flags
# (--allow-destructive-sql / --allow-destructive-ops) are passed explicitly.
# Never apply migrations automatically; a human reviews the SQL first.
set -euo pipefail

cmd="${1:-diff}"
[ "$#" -gt 0 ] && shift

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
pg_defs_sql="$repo_dir/libs/pg-defs/schema/schema.sql"
overlay_sql="$repo_dir/schema/des-web.sql"

if [ ! -f "$pg_defs_sql" ]; then
  echo "error: $pg_defs_sql not found — initialize the pg-defs submodule first:" >&2
  echo "  git submodule update --init libs" >&2
  exit 1
fi

if ! command -v dpm >/dev/null 2>&1; then
  echo "error: dpm not found on PATH." >&2
  echo "install: brew install declarative-migrations/tap/dpm" >&2
  echo "     or: curl -fsSL https://raw.githubusercontent.com/declarative-migrations/declarative-postgres-migrate.rs/main/scripts/install.sh | bash" >&2
  exit 1
fi

# Combined desired state: shared contract first, then the des-web overlay
# (overlay tables have no dependents inside pg-defs, so order is safe).
combined="$repo_dir/tmp/combined-desired-schema.sql"
mkdir -p "$repo_dir/tmp"
{
  echo "-- GENERATED by scripts/dpm.sh — do not edit."
  echo "-- Sources: libs/pg-defs/schema/schema.sql + schema/des-web.sql"
  cat "$pg_defs_sql"
  echo
  cat "$overlay_sql"
} > "$combined"

if [ -z "${SHADOW_DATABASE_URL:-}" ]; then
  echo "error: SHADOW_DATABASE_URL is required — a Postgres server URL where dpm" >&2
  echo "may create/drop throwaway databases to materialize the schema file." >&2
  echo "Local example: postgres://postgres:postgres@localhost:5432/postgres" >&2
  exit 1
fi

target="${TARGET_DATABASE_URL:-${AGENT_TASKS_RDS_DATABASE_URL:-${RDS_DATABASE_URL:-${DATABASE_URL:-${PG_DATABASE_URL:-${SUPABASE_DB_URL:-}}}}}}"

case "$cmd" in
  bootstrap)
    exec dpm bootstrap --source "$combined" "$@"
    ;;
  diff | verify | apply | review)
    if [ -z "$target" ]; then
      echo "error: no target database URL. Set TARGET_DATABASE_URL (or one of" >&2
      echo "AGENT_TASKS_RDS_DATABASE_URL, RDS_DATABASE_URL, DATABASE_URL," >&2
      echo "PG_DATABASE_URL, SUPABASE_DB_URL)." >&2
      exit 1
    fi
    # Hand the target (which carries the password) to dpm via the environment,
    # not `--target` on its argv — argv is world-readable via `ps`/procfs.
    # dpm reads TARGET_DATABASE_URL directly, so the credential never appears
    # in a process listing. Mirrors pg-defs/scripts/dpm.sh.
    export TARGET_DATABASE_URL="$target"
    exec dpm "$cmd" --source "$combined" "$@"
    ;;
  *)
    exec dpm "$cmd" "$@"
    ;;
esac
